env:
  browser: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2018
rules:
  indent:
    - error
    - 4
  quotes:
    - error
    - single
  semi:
    - error
    - always
globals:
  Backbone: true
  $: true
  _: true
