name: Fly Deploy

on:
  push:
    branches: [master]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
          with:
            version: 0.1.26
        - run: flyctl deploy --remote-only
