name: Node.js CI

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org
          cache: npm
      - run: npm ci
      - run: npm run build
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: 4.2
      - name: Start Redis
        uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: 4
      - run: nohup bash -c "npm start 2>&1 &" && sleep 10
        env:
          TESTMODE: 1
      - name: wait to start
        uses: iFaxity/wait-on-action@v1
        with:
          resource: http://localhost:8000/loginTest
      - run: npx cypress run
